#!/usr/bin/env ruby
#
# This is the executable that all Cogy-defined commands end up invoking.
#
# See http://github.com/skroutz/cogy for more.
abort("COGY_BACKEND environment variable is not set") if !ENV["COGY_BACKEND"]

require "net/http"

endpoint = ENV["COGY_BACKEND"].sub(/\/\z/,'')
uri = URI("#{endpoint}/cmd/#{ENV['COG_COMMAND']}/#{ENV['COG_CHAT_HANDLE']}")
res = Net::HTTP.post_form(uri, ENV)

puts res.body
